CREATE TABLE PACIENTE(
ID SERIAL PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
RG VARCHAR(15) NOT NULL,
DATA_NASC DATE NOT NULL,
PESO NUMERIC(3,2) NOT NULL
);

CREATE TABLE MEDICO(
CRM VARCHAR(10) PRIMARY KEY,
NOME VARCHAR(50) NOT NULL
);

CREATE TABLE SINTOMA(
ID SERIAL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
OBSERVACOES VARCHAR(255)
);

CREATE TABLE CATEGORIA(
ID SERIAL PRIMARY KEY,
TIPO VARCHAR(60) NOT NULL
);

CREATE TABLE DOENCA(
ID SERIAL PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
NOME_CIENTIFICO VARCHAR(70),
CATEGORIA INTEGER,

FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA
);

CREATE TABLE SINTOMA_DOENCA(
SINTOMA INTEGER NOT NULL,
DOENCA INTEGER NOT NULL,

PRIMARY KEY (SINTOMA, DOENCA),

FOREIGN KEY (SINTOMA) REFERENCES SINTOMA,
FOREIGN KEY (DOENCA) REFERENCES DOENCA
);

CREATE TABLE FABRICANTE(
ID SERIAL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
CNPJ CHAR(15)
);

CREATE TABLE MEDICAMENTO(
ID SERIAL PRIMARY KEY,
NOME_POPULAR VARCHAR(40) NOT NULL,
NOME VARCHAR(70),
VALOR NUMERIC(3,2),
FABRICANTE INTEGER,

FOREIGN KEY (FABRICANTE) REFERENCES FABRICANTE
);

CREATE TABLE CONSULTA(
ID SERIAL PRIMARY KEY,
DATA TIMESTAMP NOT NULL,
PACIENTE INTEGER NOT NULL,

FOREIGN KEY (PACIENTE) REFERENCES PACIENTE
);

CREATE TABLE RECEITA(
CONSULTA INTEGER NOT NULL,
MEDICAMENTO INTEGER NOT NULL,
MEDICO VARCHAR(10) NOT NULL,

PRIMARY KEY (CONSULTA, MEDICAMENTO),

FOREIGN KEY (CONSULTA) REFERENCES CONSULTA,
FOREIGN KEY (MEDICAMENTO) REFERENCES MEDICAMENTO,
FOREIGN KEY (MEDICO) REFERENCES MEDICO
);